language: node_js

node_js:
  - 7.10
  - 7

sudo: required

env:
  - GREMLINSERVER_VERSION="3.2.4"

cache:
  yarn: true

install:
  # install Oracle JDK8
  - sh -c ./build/jdk8-install.sh
  # install gremlin-server
  - sh -c ./build/gremlin-server/install.sh
  # install dependencies
  - yarn

before_script:
  - yarn build

script: yarn test

after_script:
  - yarn coverage:travis
