language: node_js

node_js:
  - 7
  - 6

sudo: required

env:
  - GREMLIN_SERVER_VERSION="3.2.4"
  - GREMLIN_SERVER_VERSION="3.1.6"

cache:
  yarn: true

install:
  - sh -c ./build/jdk8-install.sh
  - sh -c ./build/gremlin-server/install.sh
  - yarn

before_script:
  - yarn build

script: yarn test

after_script:
  - yarn coverage:travis
