language: node_js

services:
  - docker

node_js:
  - 7
  - 6

sudo: required

env:
  GREMLIN_SERVER_VERSION: 3.2.4

cache:
  yarn: true

before_install:
  - docker run -d -p 8182:8182 jbmusso/gremlin-server:$GREMLIN_SERVER_VERSION
  - docker ps -a

install:
  # - sh -c ./build/jdk8-install.sh
  # - sh -c ./build/gremlin-server/install.sh
  - yarn

before_script:
  - yarn build

script: yarn test

after_script:
  - yarn coverage:travis
